# Generated by Django 2.1 on 2018-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founding_year', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
