# Generated by Django 2.1.1 on 2018-10-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181030_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.AddField(
            model_name='competition',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Venue'),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='website.Tag'),
        ),
    ]
