# Generated by Django 2.1 on 2018-08-23 17:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180823_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
